### ISSUE TITLE
rswag command doesn't execute within a docker-compose command

### ISSUE THREAD

**Issue by hasc34** [rswag/rswag#203]
1.) I have the following setup for docker-compose.yml
```
version: '2'
services:
  api:
    image: myimage_notreal_example/myimage_notreal_example:latest
    environment:
      - MYENVIRONMENTVAR=pathto/something/this.file
    ports:
      - "3000:3000"
    depends_on:
      - swagger
    volumes:
      - .:/var/www/apps/my-api-project

  swagger:
    build: .
    image: myimage_notreal_example/myimage_notreal_example:latest
    volumes:
      - './spec:/var/www/apps/my-api-project/spec'
    command: rspec --pattern spec/integration/*_spec.rb --format Rswag::Specs::SwaggerFormatter --dry-run --order defined
    environment:
      - RAILS_ENV=development
```

2.) I have the following structure within the integration folder:
/integration/ 
	- aaa_spec.rb
	- bbb_spec.rb
	- ccc_spec.rb
	- ddd_spec.rb
3.) I run this docker-compose.yml using the command: docker-compose -f docker-compose.yml up
4.) This is the information I get from the console:
```
swagger_1  | Generating Swagger docs ...
swagger_1  | Swagger doc generated at /var/www/apps/my-api-project/swagger/v1/swagger.json
myimage_notreal_example_swagger_1 exited with code 0
```
5.) When I go into /swagger/v1/swagger.json, the files within the integration/ folder have not been generated into a json file. 
5b.) I am able to go into https://localhost:3000/api-docs and see the launched 'swagger ui'
5c.) If I go into the docker image and run the same command from the bash prompt, I am able to generate the swagger files within the integration/ folder
