### ISSUE TITLE
anyOf modifier is not being parsed for the generated UI

### ISSUE THREAD

**Issue by mochetts** [rswag/rswag#351]
I have a generated yaml file with the following shape:
```yml
                  values:
                    type: array
                    items:
                      type: object
                      properties:
                        label:
                          type: string
                          example: Some Label
                        value: <----------------- THIS PROPERTY IS IGNORED BY THE UI GENERATOR
                          anyOf: 
                          - type: string
                          - type: integer
                      required:
                      - label
                      - value
```
The idea is that this `values` property returns an array of objects with the form:
```
{ label: 'Some Label', value: 'An integer or a string' }
```

This schema follows the swagger documentation for data types:
https://swagger.io/docs/specification/data-models/data-types/

However, when looking at the generated UI, I'm seeing this:
![image](https://user-images.githubusercontent.com/3678598/88676788-e4dad180-d0c2-11ea-97db-095db0ccb179.png)

See that the `value` description containing the `anyOf` is completely ignored.
