### ISSUE TITLE
Header type missing schema around it

### ISSUE THREAD

**Issue by helderasmoreira** [rswag/rswag#398]
Hello everyone,

The current documentation on the current **2.4.0** version states under **Response headers** that the right way to use these is:
```ruby
header 'X-Rate-Limit-Limit', type: :integer, description: 'The number of allowed requests in the current period'
```

However, when doing so, the generated YAML is:
```yaml
headers:
  X-Rate-Limit-Limit:
    type: integer
    description: The number of allowed requests in the current period
```

This doesn't seem valid according to the Open API 3.0 specification where the `type` needs to be wrapped inside a `schema` field. 

```yaml
headers:
  X-Rate-Limit-Limit:
    description: The number of allowed requests in the current period.
    schema: 
      type: integer
```

A possible workaround seems to be to do it like this:
```
header 'X-Rate-Limit-Limit', schema: { type: :integer }, description: 'The number of allowed requests in the current period'
```
but since in other places the `schema` is being added automatically (in the parameter definition for instance) this seems like a bug in the implementation rather than in the documentation?
