### ISSUE TITLE
Default and format should be inside schema?

### ISSUE THREAD

**Issue by helderasmoreira** [rswag/rswag#399]
On version **2.4.0** when defining a parameter such as this

```ruby
parameter name: 'id', in: :query, type: :string, format: :email, default: 'john@doe.com', required: false
```

this is the generated output:

```YAML
- name: id
   in: query
   format: email
   default: john@doe.com
   required: false
   schema:
     type: string
```

According to the Open API 3.0 specification, the `default` and `format` should be inside the schema, no?
Something like:

```YAML
- name: id
   in: query
   required: false
   schema:
     format: email
     default: john@doe.com
     type: string
```

Am I doing something wrong or is this indeed a bug in the implementation? 
Is rswag's idea with Open API 3.0 that one does not write the `schema` and it gets added when generating?
