### ISSUE TITLE
Support for description option for "in: :body" parameter

### ISSUE THREAD

**Issue by DominikAlberski** [rswag/rswag#403]
Currently description is not visible for parameter when "in: :body" option is set.

```ruby
parameter(
  name: :bogus,
  in: :path,
  type: :string,
  description: "descryption test"
)
```
leads to:
```yaml
parameters:
- name: bogus
  in: path
  description: descryption test
```
and:
```ruby
parameter(
  name: :params,
  in: :body,
  description: descryption test
```
```yaml
requestBody:
  # missing description key here :-(
  content:
    application/json:
      schema:
```
When added manually to yaml it is properly displayed by swagger UI
