### ISSUE TITLE
[Swagger UI] Show parameter in components parameters section 

### ISSUE THREAD

**Issue by StanisLove** [rswag/rswag#417]
Could Swagger UI show a parameter defined in `components -> parameters` section described in [openApi specification](https://swagger.io/docs/specification/components/)?
E.g.
```
components:
  parameters:
    offsetParam:      # Can be referenced via '#/components/parameters/offsetParam'
      name: offset
      in: query
      description: Number of items to skip before returning the results.
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 0

```
