### ISSUE TITLE
CollectionFormat for Array Query Parameters causing Structural Errors for OpenAPI v3

### ISSUE THREAD

**Issue by smridge** [rswag/rswag#425]
Although the changes in https://github.com/optimumenergyco/rswag/pull/1 resolved the main [issue](https://github.com/rswag/rswag/issues/317). This still requires `CollectionFormat` to be used. The Swagger Editor will still work as expected (must have a backward compatibilty with v2 syntaxes). However, this still throws a `Structural Error paths...should NOT have additional properties additionalProperty: collectionFormat`.

I have tried a few different ways in altering:
```ruby
parameter(
  collectionFormat: :multi,
  in: :query,
  name: :'foos[]',
  required: false,
  schema: {type: :array, items: {type: :string}}
)
```

However, rspec fails without `collectionFormat: :multi`.

**Current YAML generates**:
```yml
- collectionFormat: multi
in: query
name: foos[]
required: false
schema:
  type: array
  items:
    type: string
```

**Should Generate**:
```yml
- in: query
name: foos[]
required: false
schema:
  type: array
  items:
    type: string
```
