### ISSUE TITLE
[BUG] Common OpenAPI linter issues on rswag generated swagger file

### ISSUE THREAD

**Issue by jrub** [rswag/rswag#600]
## Describe the bug
A couple documented elements are failing to pass common OpenAPI linters like https://github.com/Redocly/redocly-cli

### Enums

Create a request parameter with an enum like specified in the wiki https://github.com/rswag/rswag/wiki/Examples#documenting-a-query-parameter-with-a-list-of-allowed-values

Lint the `swagger.yml` output, and the generated enum will fail as _"not expected here"_.

Example:

```
 parameter name: :state, in: :query, required: false, type: :string, enum: ['outstanding', 'late', 'uncollectible', 'paid', 'refunded', 'archived'],
```
Generates
```
      - name: state
        in: query
        required: false
        enum: # this fails to pass the linter
        - outstanding
        - late
        - uncollectible
        - paid
        - refunded
        - archived
```

### Nullable: true
When using `nullable: true` in an schema, as documented in https://github.com/rswag/rswag#null-values , the result also does not pass the linter.

## Expected behavior
The expected behavior would be to pass common linters used in the OpenAPI tooling ecosystem.

Note that for **enums**, using this other way, 
```
      parameter name: :state, in: :query, required: false, schema: {
        type: :string,
        enum: ['outstanding', 'late', 'uncollectible', 'paid', 'refunded', 'archived'] 
      },
```
it creates a passing spec:
```
      - name: state
        in: query
        required: false
        schema:
          type: string
          enum:
          - outstanding
          - late
          - uncollectible
          - paid
          - refunded
          - archived
```
This way is suggested in https://github.com/rswag/rswag/wiki/Examples#documenting-a-custom-header-parameter

## Screenshots
Here is an example screenshot of the linter failing in Visual Studio Code with the Redocly OpenAPI extension:
![Example of `nullable` in a schema](https://user-images.githubusercontent.com/472092/220306367-4e1f3dce-c37e-4570-aad4-58545d90eaa9.png)

## Additional context
I'd say this might either be considered as a bug that needs changing some code behavior, or perhaps it's just a documentation problem. Either way, thanks for looking into it! 🙏

The `.redocly.yaml` file used to configured the linter rules is set to the standard `minimal` config:

```
extends:
  - minimal

apis:
  quaderno-api@v20220325:
    root: ./swagger/v20220325/swagger.yaml
    rules:
      no-ambiguous-paths: error
```

## Dependency versions
The version of are you using for:
* Rswag: rswag-api (2.5.1) , rswag-specs (2.5.1) , rswag-ui (2.5.1)
* RSpec: rspec-core (3.10.1)
* Rails: rails (7.0.4.2)
* Ruby: ruby 2.7.5p203

## Relates to which version of OAS (OpenAPI Specification)
- [ ] OAS2
- [X] OAS3
- [X] OAS3.1
