### ISSUE TITLE
[BUG] Invalid URI for nested placeholders after upgrading to 2.9.0

### ISSUE THREAD

**Issue by LakshyaKhatri** [rswag/rswag#649]
## Describe the bug
We are using nested variables in `servers.url` which was working perfectly fine, but after upgrading rswag to version `2.9.0`, we started getting this error:

```sh
URI::InvalidURIError:
        bad URI(is not URI?): "https://example.{environment}.com"
# /usr/local/bundle/gems/rswag-specs-2.9.0/lib/rswag/specs/request_factory.rb:110:in `base_path_from_servers'
      # /usr/local/bundle/gems/rswag-specs-2.9.0/lib/rswag/specs/request_factory.rb:124:in `add_path'
      # /usr/local/bundle/gems/rswag-specs-2.9.0/lib/rswag/specs/request_factory.rb:20:in `block in build_request'
      # /usr/local/bundle/gems/rswag-specs-2.9.0/lib/rswag/specs/request_factory.rb:18:in `build_request'
      # /usr/local/bundle/gems/rswag-specs-2.9.0/lib/rswag/specs/example_helpers.rb:10:in `submit_request'
      # /usr/local/bundle/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

## Steps to Test or Reproduce
When using nested variables in server configurations in `swagger.yaml`, example:

```yaml
servers:
- url: https://{defaultHost}
  description: my website
  variables:
    defaultHost:
      default: example.{environment}.com # another variable
    environment:
      default: development
      enum:
      - development
      - integration
      - candidate
```
The base URL becomes: `https://example.{environment}.com` which then throws the aforementioned `URI::InvalidURIError` error. 

## Expected behavior

The URLs generated should be one of the following, and the error should not be raised:
- **Default Case/Development:** https://example.development.com
- **Integration:** https://example.integration.com
- **Candidate:** https://example.candidate.com

## Screenshots
N/A

## Additional context
The problem is occurring because of a change that was introduced to fix `protocol` variable in #591 :
https://github.com/rswag/rswag/pull/591/files#diff-bbd8f08065700370f3c638e9dc2ba07c5af94f30dd770d7d77f2486421433b6b

After some digging I came to realize that the `base_path_from_servers` method never supported nested variables in `servers.url`. However, swagger handles them quite well:

![swagger_url](https://github.com/rswag/rswag/assets/28972442/1faa49e9-1d29-4d89-bdbc-4c27f5052254)

## Dependency versions
The version of are you using for:
* Rswag: 2.9.0
* RSpec: 
* Rails: 7.0.4.3
* Ruby: 3.2.2

## Relates to which version of OAS (OpenAPI Specification)
- [ ] OAS2
- [ ] OAS3
- [x] OAS3.1
