### ISSUE TITLE
[BUG] Unable to generate top-level tags key

### ISSUE THREAD

**Issue by dollerbill** [rswag/rswag#667]
## Describe the bug
OAS 3.1.0 supports a top-level [tags](https://swagger.io/specification/#tag-object) object that allows optional "description" fields, but I've been unable to find a way to produce this when generating yaml from Rswag 

## Steps to Test or Reproduce
Ideally, this would work when providing the tags keyword either in a path block or top-level describe block for the api
```ruby
path '/pets' do
    tags name: 'pet', description: 'Everything about your Pets'
```

or

```ruby
describe 'Pets API' do
    tags name: 'pet', description: 'Everything about your Pets'
```

both of these result in a NoMethodError:
```ruby
Failure/Error: tags name: 'pet', description: 'Everything about your Pets'

NoMethodError:
  undefined method `[]=' for nil:NilClass

            metadata[:operation][attr_name] = value
                                ^^^^^^^^^^^^^
```
## Expected behavior
Output should be similar to:
``` yaml
info:
  title: "Pet Sample"
tags:
  - name: pet
    description: Everything about your Pets
  - name: store
    description: Access to Petstore orders
paths:
  "/pets":
```

## Additional context
[Sample JSON](https://petstore.swagger.io/v2/swagger.json) showing tags object

Sample yaml with tags:
![sample yaml](https://github.com/rswag/rswag/assets/11497835/47ce6e60-1dce-4700-bbab-c70574a613ec)

## Dependency versions
The version of are you using for:
* Rswag: 2.7.0
* RSpec: 3.1.0
* Rails: 6.1.7.3
* Ruby: 3.1.0
(briefly tested with Rswag 2.10.1, issue remains)

## Relates to which version of OAS (OpenAPI Specification)
- [ ] OAS2
- [ ] OAS3
- [x] OAS3.1
