### ISSUE TITLE
[BUG] Query parameters are incorrect by using multiple object parameters

### ISSUE THREAD

**Issue by miup** [rswag/rswag#752]
## Describe the bug
If using multiple object type parameters in query, result query parameter is incorrect.

## Steps to Test or Reproduce
```rb
parameter name: :search, in: :query, schema: {
  type: :object,
  properties: {
    query: { type: :string, example: 'foo' },
    sort: { type: :string, example: 'created_at_desc' }
  }
}
parameter name: :pagination, in: :query, schema: {
  type: :object,
  properties: {
    page: { type: :integer, example: 1 },
    per: { type: :integer, example: 10 }
  }
}

response 200, 'success' do
  let(:search) { { query: 'foo', sort: 'created_at_desc' } }
  let(:page) { { page: 1, per: 10 } }
  run_test!
end
```
generated yaml is correct but requested query parameter from test is `search?query=foo&sort=created_at_desc&page=1&per=10`

```yaml
parameters:
- name: search
  in: query
  type: object
  properties:
    query:
      type: string
      example: foo
    sort:
      type: string
      example: created_at_desc
- name: page
  in: query
  type: object
  properties:
    page:
      type: integer
      example: 1
    per:
      type: integer
      example: 10
```

If these parameters are enclosed in `params`, the correct query is produced, but the yaml generated by swaggerize is enclosed in `params` as well
```rb
parameter name: :params, in: :query, schema: {
  type: :object,
  properties: {
    search: {
      type: :object,
      properties: {
        query: { type: :string, example: 'foo' },
        sort: { type: :string, example: 'created_at_desc' }
      }
    },
    pagination: {
      type: :object,
      properties: {
        page: { type: :integer, example: 1 },
        per: { type: :integer, example: 10 }
      }
    }
  }
}
response 200, 'success' do
  let(:params) { { search: { query: 'foo', sort: 'created_at_desc' }, page: { page: 1, per: 10 } } }
  run_test!
end
```
Generated yaml
```yaml
parameters:
- name: params
  in: query
  schema:
    type: object
    properties:
      search:
        type: object
        properties:
          query:
            type: string
            example: foo
          sort:
            type: string
            example: created_at_desc
      page:
        type: object
        properties:
          page:
            type: integer
            example: 1
          per:
            type: integer
            example: 10
```

## Expected behavior
Can use multiple object type query parameter without enclosing  `params`. 
`?search[query]=foo&search[sort]=created_at_desc&page[page]=1&page[per]=10`

## Dependency versions
The version of are you using for:
* Rswag: 2.13.0
* RSpec: 3.13.0
* Rails: 6.1.7.7
* Ruby: 3.0.5

## Relates to which version of OAS (OpenAPI Specification)
- [ ] OAS2
- [ ] OAS3
- [ ] OAS3.1
