### ISSUE TITLE
[BUG] Enum values in description generating only for first parameter

### ISSUE THREAD

**Issue by samenick** [rswag/rswag#806]
## Describe the bug
If method has more than one parameter with enum -- only one will have enum values in description.

## Steps to Test or Reproduce
```ruby
require 'swagger_helper'

describe 'Users API', type: :request, openapi_spec: 'admin/swagger.yaml' do
  let(:Authorization) do
    create(:admin_authentication_with_all_abilities).generate_token_for(:authorization)
  end
  
  before do
    self.class.tags 'Users'
    self.class.consumes 'application/json'
    self.class.produces 'application/json'
  end

  path '/admin/users' do
    get 'Get users list' do
      security [ authorization_header: [] ]
      parameter name: :order_param, in: :query, type: :string, required: false,
                description: 'Param name to order by',
                enum: { email: 'email', first_name: 'first name', last_name: 'last name',
                        account_type: 'type of account', created_at: 'date of creating',
                        updated_at: 'date of last update' }
      parameter name: :order_direction, in: :query, type: :string, required: false,
                description: 'Order direction',
                enum: { asc: 'ascending order', desc: 'descending order' }

      response 200, 'ok' do
        before { create(:user) }

        after { |example| write_response_example(example, response) }

        run_test!
      end
    end
  end
end
```

produces

```yaml
...
  "/admin/users":
    get:
      summary: Get users list
      security:
      - authorization_header: []
      parameters:
      - name: order_param
        in: query
        required: false
        description: "Param name to order by:\n * `email` email\n * `first_name` first
          name\n * `last_name` last name\n * `account_type` type of account\n * `created_at`
          date of creating\n * `updated_at` date of last update\n "
        enum:
          email: email
          first_name: first name
          last_name: last name
          account_type: type of account
          created_at: date of creating
          updated_at: date of last update
        schema:
          type: string
      - name: order_direction
        in: query
        required: false
        description: Order direction
        enum:
          asc: ascending order
          desc: descending order
        schema:
          type: string
      tags:
      - Users
...
```

## Expected behavior
It's might produce something this:

```yaml
...
  "/admin/users":
    get:
      summary: Get users list
      security:
      - authorization_header: []
      parameters:
      - name: order_param
        in: query
        required: false
        description: "Param name to order by:\n * `email` email\n * `first_name` first
          name\n * `last_name` last name\n * `account_type` type of account\n * `created_at`
          date of creating\n * `updated_at` date of last update\n "
        enum:
          email: email
          first_name: first name
          last_name: last name
          account_type: type of account
          created_at: date of creating
          updated_at: date of last update
        schema:
          type: string
      - name: order_direction
        in: query
        required: false
        description:  "Order direction:\n * `asc` ascending order\n * `desc` descending
          order\n "
        enum:
          asc: ascending order
          desc: descending order
        schema:
          type: string
      tags:
      - Users
...
```

## Screenshots
<img width="955" alt="Screenshot 2024-12-10 at 23 05 52" src="https://github.com/user-attachments/assets/99b3ed7a-e0d8-4cbf-85f1-3dad9a652fa5">

## Additional context
Seems like there in a bug [here](https://github.com/rswag/rswag/blob/4659911d6e68dde3fd43af27c9e905746f31d885/rswag-specs/lib/rswag/specs/swagger_formatter.rb#L77). We should filter array (not find only one parameter with `enum`) and iterate it

## Dependency versions
The version of are you using for:
* Rswag: 2.16.0
* RSpec: 3.13.2
* Rails: 8.0.0
* Ruby: 3.3.6

## Relates to which version of OAS (OpenAPI Specification)
- [x] OAS2
- [x] OAS3
- [x] OAS3.1
